{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf610
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # api/pdf.py\
from flask import send_file, request\
from reportlab.lib.pagesizes import A4\
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image\
from reportlab.lib.styles import getSampleStyleSheet\
from io import BytesIO\
\
def generate_pdf(keyword, rank, logo_url=None):\
    buffer = BytesIO()\
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=80)\
    styles = getSampleStyleSheet()\
    story = []\
\
    if logo_url:\
        try:\
            img = Image(logo_url, width=150, height=60)\
            story.append(img)\
            story.append(Spacer(1, 20))\
        except:\
            pass\
\
    story.append(Paragraph("Google UK Ranking Report", styles['Title']))\
    story.append(Spacer(1, 30))\
    story.append(Paragraph(f"Keyword: <b>\{keyword\}</b>", styles['Normal']))\
    story.append(Spacer(1, 12))\
    story.append(Paragraph(f"Current Position: <b>\{rank\}</b>", styles['Normal']))\
    story.append(Spacer(1, 12))\
    story.append(Paragraph("Report generated by RankLabel.co.uk", styles['Italic']))\
\
    doc.build(story)\
    buffer.seek(0)\
    return buffer\
\
# Add this route to your existing api/track.py\
# @app.route('/pdf', methods=['POST'])\
# def pdf():\
#     data = request.json\
#     pdf_file = generate_pdf(data['keyword'], data['rank'], data.get('logo'))\
#     return send_file(pdf_file, mimetype='application/pdf', download_name=f"\{data['keyword']\}_rank.pdf")}